apiVersion: v1
kind: PersistentVolume
metadata:
  name: filestore-nfs-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
  - ReadWriteMany
  nfs:
    path: /vol1 # e.g. /sdpvc
    server: 172.31.59.130 # e.g. 172.168.1.1
