apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: sd-minio-backendconfig
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 20
    healthyThreshold: 5
    unhealthyThreshold: 5
    requestPath: /minio/health/live
    port: 9000   # 指定要用于健康检查的端口

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sd-minio-ingress
  annotations:
    # 配置 Ingress 不进行健康检查
    # cloud.google.com/load-balancer-healthcheck: "disable"
    # cloud.google.com/neg: '{"ingress": true}'
    # 自定义健康检查
    networking.gke.io/backend-config: '{"default": "sd-minio-backendconfig"}'
spec:
  rules:
  # 跑成功--
  - host:
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-release-minio
            port:
              name: minio-console
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: my-release-minio
            port:
              name: minio-api
