apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion-train-deployment
  labels:
    app: stable-diffusion-train
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-diffusion-train
  template:
    metadata:
      labels:
        app: stable-diffusion-train
    spec:
      volumes:
        - name: stable-diffusion-storage
          persistentVolumeClaim:
            claimName: vol2
      containers:
      - name: stable-diffusion-webui
        image: us-central1-docker.pkg.dev/dave-selfstudy01/hzchen-repo/sd-webui:train
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
          - containerPort: 7860
        volumeMounts:
          - mountPath: "/stable-diffusion-webui/models"
            name: stable-diffusion-storage
            subPath: models
          - mountPath: "/stable-diffusion-webui/outputs"
            name: stable-diffusion-storage
            subPath: outputs
          - mountPath: "/inputs"
            name: stable-diffusion-storage
            subPath: inputs
