apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion-igg-deployment
  labels:
    app: stable-diffusion-igg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-diffusion-igg
  template:
    metadata:
      labels:
        app: stable-diffusion-igg
    spec:
      nodeSelector:
        cloud.google.com/gke-gpu-sharing-strategy: time-sharing
        cloud.google.com/gke-max-shared-clients-per-gpu: "2"
      volumes:
        - name: stable-diffusion-storage
          persistentVolumeClaim:
            claimName: vol2
      containers:
      - name: stable-diffusion-webui
        image: us-central1-docker.pkg.dev/dave-selfstudy01/hzchen-repo/sd-igg:0.1
        resources:
          limits:
            cpu: 1800m
            memory: 23Gi
            nvidia.com/gpu: 1
        ports:
          - containerPort: 7860
        volumeMounts:
          - mountPath: "/stable-diffusion-webui/models"
            name: stable-diffusion-storage
            subPath: models
          - mountPath: "/stable-diffusion-webui/outputs"
            name: stable-diffusion-storage
            subPath: outputs
          - mountPath: "/inputs"
            name: stable-diffusion-storage
            subPath: inputs
