kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vol2
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: filestore-nfs-pv
  resources:
    requests:
      storage: 1Ti
