# 这个dockerfile的阿里云函数版本的内存需要16个G
FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04

RUN set -ex && \
    apt update && \
    apt install -y wget git rsync libglib2.0-dev libcairo2-dev libgl1-mesa-glx && \
    rm -rf /var/lib/apt/lists/*

ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:/usr/local/cuda/lib64
RUN ln -s /usr/local/cuda/lib64/libcudart.so.11.0 /usr/local/cuda/lib64/libcudart.so

# /share是李波挂载到nfs的目录，需要和李波确认
#
ARG CUDNN_PATH=$(dirname $(/share/sdwebui_env/miniconda3/envs/sd_python310/bin/python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))
ARG TENSORRT_PATH=$(dirname $(/share/sdwebui_env/miniconda3/envs/sd_python310/bin/python -c "import tensorrt;print(tensorrt.__file__)"))
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:/usr/local/cuda/lib64:$CUDNN_PATH:$TENSORRT_PATH
#
# WORKDIR /home
# RUN rsync -azP --no-perms --no-owner --no-group --exclude '/models' --exclude '/embeddings' --exclude '/scripts' --exclude '/samples' --exclude '/localizations' --exclude '/outputs'  /share/sdwebui_env/stable-diffusion-webui/ /home/stable-diffusion-webui
# RUN chmod -Rf 777 /home/stable-diffusion-webui
# RUN ln -s /share/sdwebui_env/stable-diffusion-webui/models  /home/stable-diffusion-webui/ && \
#     ln -s /share/sdwebui_env/stable-diffusion-webui/embeddings  /home/stable-diffusion-webui/ && \
#     ln -s /share/sdwebui_env/stable-diffusion-webui/scripts  /home/stable-diffusion-webui/ && \
#     ln -s /share/sdwebui_env/stable-diffusion-webui/samples  /home/stable-diffusion-webui/ && \
#     ln -s /share/sdwebui_env/stable-diffusion-webui/localizations  /home/stable-diffusion-webui/ && \
#     ln -s /share/sdwebui_env/stable-diffusion-webui/outputs  /home/stable-diffusion-webui/
#
EXPOSE 7860

WORKDIR /home
# WORKDIR /share/sdwebui_env/stable-diffusion-webui
# --ui-settings-file /home/stable-diffusion-webui/config.json
# CMD ["/share/sdwebui_env/miniconda3/envs/sd_python310/bin/python", "launch.py", "--listen", "--xformers",  "--medvram"]
CMD /bin/sh -c "rsync -azP --no-perms --no-owner --no-group --exclude '/models' --exclude '/embeddings' --exclude '/scripts' --exclude '/samples' --exclude '/localizations' --exclude '/outputs'  /share/sdwebui_env/stable-diffusion-webui/ /home/stable-diffusion-webui && cd /home/stable-diffusion-webui && ln -s /share/sdwebui_env/stable-diffusion-webui/models  /home/stable-diffusion-webui/ && ln -s /share/sdwebui_env/stable-diffusion-webui/embeddings  /home/stable-diffusion-webui/ && ln -s /share/sdwebui_env/stable-diffusion-webui/scripts  /home/stable-diffusion-webui/ && ln -s /share/sdwebui_env/stable-diffusion-webui/samples  /home/stable-diffusion-webui/ &&  ln -s /share/sdwebui_env/stable-diffusion-webui/localizations  /home/stable-diffusion-webui/ && ln -s /share/sdwebui_env/stable-diffusion-webui/outputs  /home/stable-diffusion-webui/ && /share/sdwebui_env/miniconda3/envs/sd_python310/bin/python launch.py --listen --xformers --medvram"