
# /home/miniconda3/envs/sd_python310/bin/python -m pip install virtualenv 或者 /home/miniconda3/bin/conda install -n sd_python310 virtualenv
# && /home/miniconda3/envs/sd_python310/bin/python  launch_gcp.py --skip-torch-cuda-test  \ 原来用这个，后来改为python -c的方式
# 使用 --skip-torch-cuda-test, 因为cloudbuild.yaml的machineType是没有GPU的； 另一种思路，取消这个参数，但是cloudbuild.yaml的machineType改成有GPU的也可以尝试下；----可以用打好的镜像创建一个ubuntu的pod参考deployment_ubuntu_sd_test.yaml进行调试
# 独立部署时， 如果出现安装gfpgan报错，可以先尝试安装/home/miniconda3/envs/sd_python310/bin/python -m pip install cython==0.29.34
#
# AddNet如何报错，可能是lora的的模型不完整，删除不完整的lora即可----重要
# 
# 安装Auto-Photoshop-StableDiffusion-Plugin插件
# git clone https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin
# cd Auto-Photoshop-StableDiffusion-Plugin
# git checkout 745d541a6298ce58ea8a135349978c864106836d
# pip install -r requirements.txt  # 可以不执行，启动sdwebui会自动执行
# 修改
# /Users/yuanxiao/workspace/0yxgithub/Auto-Photoshop-StableDiffusion-Plugin/install.py
# auto_update=False # 否则会自动更新
#
# 一些插件需要用到的命令
# sd-webui-additional-networks ----- 暂时不安装 -----
# echo ---------start ln additional networks-------$(date +"%Y-%m-%d %H:%M:%S")--------------- && \
# rm -rf /home/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/* && \
# ln -s /mnt/sdwebui_public/public/models/Lora  /home/stable-diffusion-webui/extensions/sd-webui-additional-networks/models/lora/
#
# 成功版本记录: 
# https://github.com/yuan6785/stable-diffusion-webui.git

#
# 升级到最新版本的命令:-------重要
# cd stable-diffusion-webui; git checkout develop; git add .; git commit  -am "1"; git checkout master; git pull; git checkout develop; git merge v1.5.0  # 这里的v1.5.0也可以其他的commit号a3ddf464a2ed24c999f67ddfef7969f8291567be
# python -c "import launch;launch.prepare_environment();"  安装第三方包

# 上一个成功版本 ： branch:20230515 submit:   e4cd0e1abc89713d7c1ac7f1f37ea8359c49d7ec
# 目前版本:  branch:master   submit:  a3ddf464a2ed24c999f67ddfef7969f8291567be
#
RUN set -ex \
    && bash Miniconda3-py38_23.1.0-1-Linux-x86_64.sh -b -p /home/miniconda3 \
    && /home/miniconda3/bin/conda init \
    && /home/miniconda3/bin/conda create -y --name stable-diffusion-webui-20230713 python=3.10 \
    && /home/miniconda3/bin/conda install -y -n stable-diffusion-webui-20230713 virtualenv \
    && git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui \
    && cd stable-diffusion-webui \
    && git checkout -b develop f865d3e11647dfd6c7b2cdf90dde24680e58acd8 \
    && /home/miniconda3/envs/stable-diffusion-webui-20230713/bin/python -m pip install cython==0.29.36 \
    && /home/miniconda3/envs/stable-diffusion-webui-20230713/bin/python -c "import launch;launch.prepare_environment();" --skip-torch-cuda-test \
    && cd extensions \
    && git clone https://github.com/Mikubill/sd-webui-controlnet.git && cd sd-webui-controlnet && git checkout -b develop 098f6cd887ac5f6f5f0e7cc9d81460095d2be012 && cd .. \
    && git clone https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git && cd a1111-sd-webui-lycoris && git checkout -b develop  8e97bf54867c25d00fc480be1ab4dae5399b35ef && cd .. \
    && git clone https://github.com/DominikDoom/a1111-sd-webui-tagcomplete.git && cd a1111-sd-webui-tagcomplete && git checkout -b develop 2.6.0 && cd .. \
    && git clone https://github.com/fkunn1326/openpose-editor && cd openpose-editor && git checkout -b develop  722bca6fb9b062815d13b950e7040589abaec797 && cd .. \
    && git clone https://github.com/hnmr293/posex && cd posex && git checkout -b develop 292f92d5068046f988fe002eb0a43b8841ad449e && cd .. \
    && git clone https://github.com/kohya-ss/sd-webui-additional-networks && cd sd-webui-additional-networks && git checkout -b develop v0.5.0 && cd .. \
    && git clone https://github.com/jexom/sd-webui-depth-lib.git && cd sd-webui-depth-lib && git checkout -b develop  efa9f616b30ea0f27e5dadf40ab41815012d1d78 && cd .. \
    && git clone https://github.com/Coyote-A/ultimate-upscale-for-automatic1111.git && cd ultimate-upscale-for-automatic1111 && git checkout -b develop c99f382b31509b87b4d512e70e9caf08ae7a079f && cd .. 

####################################################################################################################################
--- 激活conda环境
/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/bin/conda init
source ~/.bashrc

--- 重要版本修改(因为a1111-sd-webui-locon不维护了) 
--现在命令行启动参数(--lyco-debug --lyco-patch-lora --lyco-dir ./models/Lora), 这样启动就可以替换原来的a1111-sd-webui-locon插件了，连提示词都不用改
https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris.git@8e97bf54867c25d00fc480be1ab4dae5399b35ef 代替原来的 https://github.com/KohakuBlueleaf/a1111-sd-webui-locon.git@b6911354f7641c49296b37a2b939c3c472624abc
####################################################################################################################################


####################################################################################################################################
重要步骤: 调试
--------------------------------------------------------------------------------------------------
# 调试:  (部署到云函数参考 readme_debug.txt)
# 调试: 先到原来的版本调试生产必要的目录(models下的目录比如GFPGAN等)和安装对应版本的xformers
# 重要参数 --skip-prepare-environment  可以跳过prepare_environment()函数,包含插件(插件目录的install.py文件)的的第三方安装都不会运行-我已经测试过了,不然会重新安装一些东西，耗时较长
# 如果有新插件需要安装，则不能要这个参数，因为插件也有第三方包需要安装
# 有预安装的命令--有新插件第一次运行这个 
cd /mnt/sdwebui_public/versions/sdwebui_env/stable-diffusion-webui-20230713/stable-diffusion-webui
/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/envs/sd_python310_20230713/bin/python  launch.py  --listen --port 9965  --xformers  --medvram \
--lyco-debug --lyco-patch-lora --lyco-dir ./models/Lora
--------------------------------------------------------------------------------------------------
# 调试:  (部署到云函数参考 readme_debug.txt)
# 无预安装的命令--无新插件后面都运行这个，更快
cd /mnt/sdwebui_public/versions/sdwebui_env/stable-diffusion-webui-20230713/stable-diffusion-webui
/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/envs/sd_python310_20230713/bin/python  launch.py --listen --port 9965  --xformers  --medvram \
--lyco-debug --lyco-patch-lora --lyco-dir ./models/Lora  \
--skip-prepare-environment  
--------------------------------------------------------------------------------------------------
# 调试(----废弃---已经合并到主分支，主分支v1.5.0已经支持sdxl， 虽然废弃，但下面的注释也是很好的参考):
# 参考: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/11757
# sdxl的分支需要--no-half-vae (sdxl是1024*1024的默认分辨率--这个分辨率才能出非常好的效果，否则的话生成的图很乱,效果也不好)---阿里云需要开ecs.gn6i-c16g1.4xlarge 64GB内存以上的机器 # --
# sdxl的分支的commit号: dc3906185656dae75fcefe96625b1dcd0d31579c 14cf434bc36d0ef31f31d4c6cd2bd15d7857d5c8
# -- 可以选择我下的vae(改变vae需要重启sd)--好像vae无效---
cd /mnt/sdwebui_public/versions/sdwebui_env/stable-diffusion-webui-sdxl-20230715/stable-diffusion-webui
/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/envs/sdxl_python310_20230715/bin/python launch.py  --listen --port 9965 --no-half-vae  --medvram \
--lyco-debug --lyco-patch-lora --lyco-dir ./models/Lora \
--skip-prepare-environment
--------------------------------------------------------------------------------------------------
# 调试:  最新的sd版本-----测试用(每次用sd最新版本测试即可)-----
# 预安装需要的包--
# /mnt/sdwebui_public/versions/sdwebui_env/miniconda3/envs/sd_python310_lastest/bin/python -c "import launch;launch.prepare_environment();"
# 调试: 先到原来的版本调试生产必要的目录(models下的目录比如GFPGAN等)和安装对应版本的xformers
# 重要参数 --skip-prepare-environment  可以跳过prepare_environment()函数,包含插件(插件目录的install.py文件)的的第三方安装都不会运行-我已经测试过了,不然会重新安装一些东西，耗时较长
# 如果有新插件需要安装，则不能要这个参数，因为插件也有第三方包需要安装
# 有预安装的命令--有新插件第一次运行这个 
cd /mnt/sdwebui_public/versions/sdwebui_env/stable-diffusion-webui-latest/stable-diffusion-webui
/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/envs/sd_python310_lastest/bin/python  launch.py  --listen --port 9001  --xformers  --medvram \
--lyco-debug --lyco-patch-lora --lyco-dir ./models/Lora \
--skip-prepare-environment
--------------------------------------------------------------------------------------------------
# 调试: （部署到ecs参考笔记[stablediffusionwebui安装过程之阿里云dreambooth-新版本nas版本]）
# dreambooth训练的模型(第一次运行不要用--skip-prepare-environment，因为有新插件需要安装)---
# 该版本的sd安装太爽了，没有各种报错，也不用降级torch了---sd version: v1.4.1  •  python: 3.10.12  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0-------按上面dockerfile的版本安装即可----
# 安装：git clone  https://github.com/d8ahazard/sd_dreambooth_extension && cd sd_dreambooth_extension && git checkout -b develop  c2a5617c587b812b5a408143ddfb18fc49234edf && cd ..
# 解决undefined symbol: cudaRuntimeGetVersion的报错需要到conda activate sd_python310_20230713_train环境下:
# conda install cudatoolkit==11.8.0  # 执行的时候需要进入conda环境才行，就算python路径带有conda环境也不行，必须是activate的环境
# 解决方法：加下面这句即可----重要-----
# /bin/sh -c '/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/bin/conda init;chmod +x ~/.bashrc;. ~/.bashrc;eval "$(/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/bin/conda shell.bash hook)";conda activate sd_python310_20230713_train;python -c "import sys; print(sys.executable)"'
/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/bin/conda init;chmod +x ~/.bashrc;. ~/.bashrc;eval "$(/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/bin/conda shell.bash hook)";conda activate sd_python310_20230713_train;python -c "import sys; print(sys.executable)"
cd /mnt/sdwebui_public/versions/sdwebui_env/stable-diffusion-webui-dreambooth-20230724/stable-diffusion-webui
/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/envs/sd_python310_20230713_train/bin/python  launch.py   --listen --port 9965  --xformers  --medvram  \
--lyco-debug --lyco-patch-lora --lyco-dir ./models/Lora \
--skip-prepare-environment
后台运行(记得加-u，否则日志无法输出)---
/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/bin/conda init;chmod +x ~/.bashrc;. ~/.bashrc;eval "$(/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/bin/conda shell.bash hook)";conda activate sd_python310_20230713_train;python -c "import sys; print(sys.executable)"
cd /mnt/sdwebui_public/versions/sdwebui_env/stable-diffusion-webui-dreambooth-20230724/stable-diffusion-webui
nohup /mnt/sdwebui_public/versions/sdwebui_env/miniconda3/envs/sd_python310_20230713_train/bin/python -u launch.py   --listen --port 9965  --xformers  --medvram \
--lyco-debug --lyco-patch-lora --lyco-dir ./models/Lora  \
--skip-prepare-environment > nohup.out 2>&1 &
tail -f nohup.out
杀死服务---
kill -9 $(ps -ef|grep launch.py|grep -v grep|awk '{print $2}')
ps -ef|grep launch.py
--------------------------------------------------------------------------------------------------
####################################################################################################################################



####################################################################################################################################
模拟云函数环境进行调试--------------------------sd_python310_20230713-----------------------
另外一种调试方法(带GPU的)--------复制到home目录模拟云函数环境进行调试---------
我的调试镜像打包好的:  sdwebui-aliynfunc-nas-debug（含GPU的）。
实例启动模板: sdwebui-aliynfunc-nas-debug （用上面的镜像和相关机型的，直接用即可）--------
--------------到带gpu的服务器执行下面命令（pip install tensorrt==8.6.0）----------------

/bin/sh -c 'echo ---------start-------$(date +"%Y-%m-%d %H:%M:%S")--------------- && \
echo ---------start set env-------$(date +"%Y-%m-%d %H:%M:%S")--------------- && \
CUDNN_PATH=$(dirname $(/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/envs/sd_python310_20230713/bin/python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)")) && \
TENSORRT_PATH=$(dirname $(/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/envs/sd_python310_20230713/bin/python -c "import tensorrt;print(tensorrt.__file__)")) && \
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:$CUDNN_PATH:$TENSORRT_PATH && \
echo ---------start rsync-------$(date +"%Y-%m-%d %H:%M:%S")--------------- && \
if [ ! -d "/home/stable-diffusion-webui/modules" ]; then rsync -azP --no-perms --no-owner --no-group --exclude "/models" --exclude "/embeddings" --exclude "/scripts" --exclude "/samples" --exclude "/localizations" --exclude "/outputs"  /mnt/sdwebui_public/versions/sdwebui_env/stable-diffusion-webui-20230713/stable-diffusion-webui/ /home/stable-diffusion-webui; fi && \
echo ---------start ln base-------$(date +"%Y-%m-%d %H:%M:%S")--------------- && \
if [ ! -d "/home/stable-diffusion-webui/models" ]; then mkdir /home/stable-diffusion-webui/models; fi && \
for dir in Codeformer deepbooru ESRGAN GFPGAN  karlo LDSR SwinIR VAE-approx; do if [ ! -L "/home/stable-diffusion-webui/models/$dir" ]; then ln -s /mnt/sdwebui_public/versions/sdwebui_env/stable-diffusion-webui-20230713/stable-diffusion-webui/models/$dir  /home/stable-diffusion-webui/models/; fi; done && \
for dir in ControlNet  hypernetworks  Lora  Stable-diffusion  VAE; do if [ ! -L "/home/stable-diffusion-webui/models/$dir" ]; then ln -s /mnt/sdwebui_public/public/models/$dir  /home/stable-diffusion-webui/models/; fi; done && \
for dir in embeddings  localizations  outputs  samples  scripts; do if [ ! -L "/home/stable-diffusion-webui/$dir" ]; then ln -s /mnt/sdwebui_public/public/$dir  /home/stable-diffusion-webui/; fi; done && \
echo ---------end-------$(date +"%Y-%m-%d %H:%M:%S")---------------
'
启动(可以在home目录下自行调试，不影响云函数的运行)---
cd /home/stable-diffusion-webui
/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/envs/sd_python310_20230713/bin/python  launch.py  --listen --port 9965  --xformers  --medvram --lyco-debug --lyco-patch-lora --lyco-dir ./models/Lora  --skip-prepare-environment

调试完成后: 删除/home/stable-diffusion-webui即可
####################################################################################################################################







####################################################################################################################################
模拟ecs环境进行调试--------------------------sd_python310_20230713_train-----------------------
另外一种调试方法(带GPU的)--------复制到home目录模拟云函数环境进行调试---------
我的调试镜像打包好的:  sdwebui-aliynfunc-nas-debug（含GPU的）。
实例启动模板: sdwebui-aliynfunc-nas-debug （用上面的镜像和相关机型的，直接用即可）--------
--------------到带gpu的服务器执行下面命令（pip install tensorrt==8.6.0）----------------

/bin/sh -c 'echo ---------start-------$(date +"%Y-%m-%d %H:%M:%S")--------------- && \
echo ---------start set env-------$(date +"%Y-%m-%d %H:%M:%S")--------------- && \
CUDNN_PATH=$(dirname $(/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/envs/sd_python310_20230713_train/bin/python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)")) && \
TENSORRT_PATH=$(dirname $(/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/envs/sd_python310_20230713_train/bin/python -c "import tensorrt;print(tensorrt.__file__)")) && \
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64:$CUDNN_PATH:$TENSORRT_PATH && \
echo ---------start rsync-------$(date +"%Y-%m-%d %H:%M:%S")--------------- && \
if [ ! -d "/home/stable-diffusion-webui/modules" ]; then rsync -azP --no-perms --no-owner --no-group --exclude "/models" --exclude "/embeddings" --exclude "/scripts" --exclude "/samples" --exclude "/localizations" --exclude "/outputs"  /mnt/sdwebui_public/versions/sdwebui_env/stable-diffusion-webui-dreambooth-20230724/stable-diffusion-webui/ /home/stable-diffusion-webui; fi && \
echo ---------start ln base-------$(date +"%Y-%m-%d %H:%M:%S")--------------- && \
if [ ! -d "/home/stable-diffusion-webui/models" ]; then mkdir /home/stable-diffusion-webui/models; fi && \
for dir in Codeformer deepbooru ESRGAN GFPGAN  karlo LDSR SwinIR VAE-approx; do if [ ! -L "/home/stable-diffusion-webui/models/$dir" ]; then ln -s /mnt/sdwebui_public/versions/sdwebui_env/stable-diffusion-webui-dreambooth-20230724/stable-diffusion-webui/models/$dir  /home/stable-diffusion-webui/models/; fi; done && \
for dir in ControlNet  hypernetworks  Stable-diffusion  VAE; do if [ ! -L "/home/stable-diffusion-webui/models/$dir" ]; then ln -s /mnt/sdwebui_public/public/models/$dir  /home/stable-diffusion-webui/models/; fi; done && \
if [ ! -d "/home/stable-diffusion-webui/models/Lora" ]; then mkdir /home/stable-diffusion-webui/models/Lora; fi && \
for dir in embeddings  localizations  outputs  samples  scripts; do if [ ! -L "/home/stable-diffusion-webui/$dir" ]; then ln -s /mnt/sdwebui_public/public/$dir  /home/stable-diffusion-webui/; fi; done && \
echo ---------end-------$(date +"%Y-%m-%d %H:%M:%S")---------------
'

启动(可以在home目录下自行调试，不影响云函数的运行)---LD_LIBRARY_PATH的值是上面命令行最后一行的值,不然训练会报错，后面下面的命令加上上面的命令里面即可---------

/bin/sh -c '/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/bin/conda init;chmod +x ~/.bashrc;. ~/.bashrc;eval "$(/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/bin/conda shell.bash hook)";conda activate sd_python310_20230713_train;python -c "import sys; print(sys.executable)" && \
cd /home/stable-diffusion-webui && \
/mnt/sdwebui_public/versions/sdwebui_env/miniconda3/envs/sd_python310_20230713_train/bin/python  launch.py  --listen --port 9965  --xformers  --medvram --lyco-debug --lyco-patch-lora --lyco-dir ./models/Lora  --skip-prepare-environment
'

调试完成后: 删除/home/stable-diffusion-webui即可

####################################################################################################################################