steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '${_BUILD_REPO}']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gsutil'
    args: ['cp', 'gs://${_BUILD_BUCKET}/${_BUILD_MODEL}/model.ckpt', 'gcp-stable-diffusion-build-deploy/Stable-Diffusion-UI-Novel/model.ckpt']
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'gcp-stable-diffusion-build-deploy/Stable-Diffusion-UI-Novel'
    args: ['build', '-t', 'us-docker.pkg.dev/${PROJECT_ID}/${_BUILD_REGIST}/stable-diffusion-${_BUILD_MODEL}', '.']
images: ['us-docker.pkg.dev/${PROJECT_ID}/${_BUILD_REGIST}/stable-diffusion-${_BUILD_MODEL}']
substitutions:
  _BUILD_REPO: $(body.message.buildrepo)
  _BUILD_BUCKET: $(body.message.buildbucket)
  _BUILD_MODEL: $(body.message.buildmodel)
  _BUILD_REGIST: $(body.message.buildregist)
options:
  machineType: 'N1_HIGHCPU_8'
  diskSizeGb: '200'
