apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: stable-diffusion-cd
description: main application pipeline
serialPipeline:
 stages:
 - targetId: prod
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod
description: production cluster
gke:
 cluster: projects/<project_id>/locations/<region>/clusters/<cluster_name>