apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-workload
  labels:
    app: gpu-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-workload
  template:
    metadata:
      labels:
        app: gpu-workload
    spec:
      containers:
      - name: gpu-workload
        image: nvcr.io/nvidia/k8s/dcgm-exporter:2.3.4-2.6.4-ubuntu20.04
        command: ["/bin/bash", "-c", "--"]
        args: 
          - while true; do
              dcgmproftester11 --duration 120 --fieldId 1002 --no-dcgm-validation;
              dcgmproftester11 --duration 120 --fieldId 1003 --no-dcgm-validation;
              dcgmproftester11 --duration 120 --fieldId 1004 --no-dcgm-validation;
              dcgmproftester11 --duration 120 --fieldId 1005 --no-dcgm-validation;
              dcgmproftester11 --duration 120 --fieldId 1006 --no-dcgm-validation;
              dcgmproftester11 --duration 120 --fieldId 1007 --no-dcgm-validation;
              dcgmproftester11 --duration 120 --fieldId 1008 --no-dcgm-validation;
              dcgmproftester11 --duration 120 --fieldId 1009 --no-dcgm-validation;
              dcgmproftester11 --duration 120 --fieldId 1010 --no-dcgm-validation;
            done;
        resources:
          limits:
            nvidia.com/gpu: 1