apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-stable-diffusion-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard-rwo