apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: gpugke
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/cliu201/docker-repo/stable-diffusion-novel
    context: Stable-Diffusion-UI-Novel
    docker:
      dockerfile: Dockerfile
  googleCloudBuild:
    projectId: cliu201
    diskSizeGb: 200
    machineType: N1_HIGHCPU_8
deploy:
  # kubectl:
  #   manifests:
  #   - Stable-Diffusion-UI-Novel/kubernetes/deployment.yaml
  #   - Stable-Diffusion-UI-Novel/kubernetes/pvc.yaml
  #   - Stable-Diffusion-UI-Novel/kubernetes/service.yaml
  kustomize:
    paths:
      - Stable-Diffusion-UI-Novel/kubernetes
