network: projects/886724937990/global/networks/myvpc-ipv6
workerPoolSpecs:
    - machineSpec:
        machineType: a2-highgpu-1g
        acceleratorType: NVIDIA_TESLA_A100
        acceleratorCount: 1
      diskSpec:
        bootDiskType: pd-ssd
        bootDiskSizeGb: 200
      replicaCount: 1
      containerSpec:
        imageUri: us-central1-docker.pkg.dev/dave-selfstudy01/hzchen-repo/sd-webui:vertex