# # 多个镜像构建---其实还是依次构建
# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'us-central1-docker.pkg.dev/happyaigc/sd-web-ui-artifacts/sd-webui:inference2', '-f', 'Dockerfile.root.ancondapython.nginx.supervisor.yx', '.' ]
# - name: 'gcr.io/cloud-builders/docker'
#   args: [ 'build', '-t', 'us-central1-docker.pkg.dev/happyaigc/sd-web-ui-artifacts/sd-webui:inference3', '-f', 'Dockerfile.root.ancondapython.yx', '.' ]
# options:
#   machineType: 'E2_HIGHCPU_8'
#   diskSizeGb: '200'
# images: ['us-central1-docker.pkg.dev/happyaigc/sd-web-ui-artifacts/sd-webui:inference2', 'us-central1-docker.pkg.dev/happyaigc/sd-web-ui-artifacts/sd-webui:inference3']

# 一个镜像构建
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/happyaigc/sd-web-ui-artifacts/sd-webui:inference3', '-f', 'Dockerfile.root.ancondapython.yx', '.' ]
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '200'
images: ['us-central1-docker.pkg.dev/happyaigc/sd-web-ui-artifacts/sd-webui:inference3']