steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/happyaigc/sd-web-ui-artifacts/sd-webui:inference2', '-f', 'Dockerfile.root.ancondapython.supervisor', '.' ]
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: '200'
images: ['us-central1-docker.pkg.dev/happyaigc/sd-web-ui-artifacts/sd-webui:inference2']