---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sd-nginx-configmap
data:
  nginx-config.conf: |
    upstream proxy_sdwebui_sd15
    {
      server sd-service-sd15:8080;
    }
    upstream proxy_sdwebui_dreamworld
    {
      server sd-service-dreamworld:8080;
    }
    server
    {
      listen 8080;
      server_name .*;  # 这个特别重要，如果用ip访问，需要改为ip，如果是域名访问需要修改为域名
      location /sd15
      {
        proxy_pass http://proxy_sdwebui_sd15;
        rewrite /sd15/(.*) /$1  break;
        proxy_redirect     off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;  # websocket
        proxy_set_header Connection "Upgrade";   # websocket
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
        client_max_body_size 100m;
        #
        proxy_set_header   Connection       "";   # 如果是supervisord的代理---logtail才能访问
        proxy_http_version 1.1;    # 如果是supervisord的代理---logtail才能访问
        proxy_connect_timeout              60s;
        proxy_send_timeout                 60s;
        proxy_read_timeout                 60s;
      }

      location /dreamworld
      {
        proxy_pass http://proxy_sdwebui_dreamworld;
        rewrite /dreamworld/(.*) /$1  break;
        proxy_redirect     off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;  # websocket
        proxy_set_header Connection "Upgrade";   # websocket
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        access_log off;
        client_max_body_size 100m;
        #
        proxy_set_header   Connection       "";   # 如果是supervisord的代理---logtail才能访问
        proxy_http_version 1.1;    # 如果是supervisord的代理---logtail才能访问
        proxy_connect_timeout              60s;
        proxy_send_timeout                 60s;
        proxy_read_timeout                 60s;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: sd-nginx
spec:
  containers:
  - name: sd-nginx
    image: k8s.gcr.io/nginx-slim:0.8
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx/conf.d
  volumes:
  - name: nginx-conf
    configMap:
      name: nginx-configmap
      items:
      - key: nginx-config.conf
        path: nginx.conf

