apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backendconfig-dreamworld
spec:
  # sessionAffinity: # 用ip来固定负载均衡的pod
  #   affinityType: "CLIENT_IP"  
  sessionAffinity: # 用用GENERATED_COOKIE来固定负载均衡的pod
    affinityType: "GENERATED_COOKIE"  # HTTP_COOKIE
    affinityCookieTtlSec: 0
---
apiVersion: v1
kind: Service
metadata:
  name: dreamworld-web
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8080":"my-backendconfig-dreamworld"}}'
    # cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 7860
  selector:
    app: stable-diffusion-dreamworld
  # type: NodePort
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dreamworld-ingress
spec:
  defaultBackend:
    service:
      name: dreamworld-web
      port:
        number: 8080