apiVersion: v1
kind: Service
metadata:
  name: ubuntu-2204-service
spec:
  selector:
    app: ubuntu-2204
  ports:
    - name: ftp
      protocol: TCP
      port: 21
      targetPort: 21
    # - name: passive-ports
    #   protocol: TCP
    #   port: 20000-20045
    #   targetPort: 20000-20045
    - name: passive-ports-20000
      protocol: TCP
      port: 20000
      targetPort: 20000
    - name: passive-ports-20001
      protocol: TCP
      port: 20001
      targetPort: 20001
    - name: passive-ports-20002
      protocol: TCP
      port: 20002
      targetPort: 20002
    - name: passive-ports-20003
      protocol: TCP
      port: 20003
      targetPort: 20003
    - name: passive-ports-20004
      protocol: TCP
      port: 20004
      targetPort: 20004
    - name: passive-ports-20005
      protocol: TCP
      port: 20005
      targetPort: 20005
    - name: passive-ports-20006
      protocol: TCP
      port: 20006
      targetPort: 20006
    - name: passive-ports-20007
      protocol: TCP
      port: 20007
      targetPort: 20007
    - name: passive-ports-20008
      protocol: TCP
      port: 20008
      targetPort: 20008
    - name: passive-ports-20009
      protocol: TCP
      port: 20009
      targetPort: 20009
    - name: passive-ports-20010
      protocol: TCP
      port: 20010
      targetPort: 20010
    - name: passive-ports-20011
      protocol: TCP
      port: 20011
      targetPort: 20011
    - name: passive-ports-20012
      protocol: TCP
      port: 20012
      targetPort: 20012
    - name: passive-ports-20013
      protocol: TCP
      port: 20013
      targetPort: 20013
    - name: passive-ports-20014
      protocol: TCP
      port: 20014
      targetPort: 20014
    - name: passive-ports-20015
      protocol: TCP
      port: 20015
      targetPort: 20015
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ubuntu-2204-ingress
spec:
  rules:
    # - host: vsftpd.example.com # 将此值更改为您的域名
    - host:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ubuntu-2204-service
                port:
                  name: ftp 