# apiVersion: v1
# kind: Service
# metadata:
#   name: ubuntu-2204-service
# spec:
#   selector:
#     app: ubuntu-2204
#   ports:
#     - name: ftp
#       protocol: TCP
#       port: 21
#       targetPort: 21
#     - name: passive-ports-20000
#       protocol: TCP
#       port: 20000
#       targetPort: 20000
#     - name: passive-ports-20001
#       protocol: TCP
#       port: 20001
#       targetPort: 20001
#     - name: passive-ports-20002
#       protocol: TCP
#       port: 20002
#       targetPort: 20002
#     - name: passive-ports-20003
#       protocol: TCP
#       port: 20003
#       targetPort: 20003
#   type: ClusterIP
# ---
# apiVersion: networking.k8s.io/v1
# kind: NetworkPolicy
# metadata:
#   name: ubuntu-2204-networkpolicy
#   namespace: default
# spec:
#   podSelector:
#     matchLabels:
#       app: ubuntu-2204
#   policyTypes:
#     - Ingress
#     - Egress
#   ingress:
#     - from:
#         - podSelector: {}
#         - ipBlock:
#             cidr: 0.0.0.0/0
#       ports:
#         - protocol: TCP
#           port: 21
#         # - protocol: TCP
#         #   port: 30000
#         #   endPort: 30003
#         - protocol: TCP
#           port: 30000
#         - protocol: TCP
#           port: 30001
#         - protocol: TCP
#           port: 30002
#         - protocol: TCP
#           port: 30003
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ubuntu-2204-configmap
  namespace: default
data:
  21: "ubuntu-2204-service:21"
  30000: "ubuntu-2204-service:30000"
  30001: "ubuntu-2204-service:30001"
  30002: "ubuntu-2204-service:30002"
  30003: "ubuntu-2204-service:30003"
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-2204-service
  namespace: default
  labels:
    app.kubernetes.io/name: ubuntu-2204-service
    app.kubernetes.io/part-of: ubuntu-2204-service
spec:
  type: LoadBalancer
  ports:
    - name: ftp
      port: 21
      targetPort: 21
      protocol: TCP
    - name: passive-30000
      port: 30000
      targetPort: 30000
      protocol: TCP
    - name: passive-30001
      port: 30001
      targetPort: 30001
      protocol: TCP
    - name: passive-30002
      port: 30002
      targetPort: 30002
      protocol: TCP
    - name: passive-30003
      port: 30003
      targetPort: 30003
      protocol: TCP
  selector:
    app: ubuntu-2204

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ubuntu-2204-ingress
#   annotations:
#     nginx.org/stream: "true"
#     nginx.org/tcp-services: "21:ubuntu-2204-service,20000:ubuntu-2204-service,20001:ubuntu-2204-service,20002:ubuntu-2204-service,20003:ubuntu-2204-service"
# spec:
#   rules:
#   - host: 
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: ubuntu-2204-service
#             port:
#               number: 21
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: ubuntu-2204-service
#             port:
#               number: 20000
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: ubuntu-2204-service
#             port:
#               number: 20001
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: ubuntu-2204-service
#             port:
#               number: 20002
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: ubuntu-2204-service
#             port:
#               number: 20003

