---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ubuntu-2204-configmap
  namespace: default
data:
  21: "ubuntu-2204-service:21"
  30000: "ubuntu-2204-service:30000"
  30001: "ubuntu-2204-service:30001"
  30002: "ubuntu-2204-service:30002"
  30003: "ubuntu-2204-service:30003"
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-2204-service
  namespace: default
  labels:
    app.kubernetes.io/name: ubuntu-2204-service
    app.kubernetes.io/part-of: ubuntu-2204-service
spec:
  type: LoadBalancer
  ports:
    - name: ftp
      port: 21
      targetPort: 21
      protocol: TCP
    - name: passive-30000
      port: 30000
      targetPort: 30000
      protocol: TCP
    - name: passive-30001
      port: 30001
      targetPort: 30001
      protocol: TCP
    - name: passive-30002
      port: 30002
      targetPort: 30002
      protocol: TCP
    - name: passive-30003
      port: 30003
      targetPort: 30003
      protocol: TCP
  selector:
    app: ubuntu-2204



