apiVersion: apps/v1
kind: Deployment
metadata:
  name: sd-deployment-sd15  # change_other_model
  labels:
    app: sd-sd15 # change_other_model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sd-sd15 # change_other_model
  template:
    metadata:
      labels:
        app: sd-sd15 # change_other_model
    spec:
      nodeSelector:
        cloud.google.com/gke-gpu-sharing-strategy: time-sharing
        cloud.google.com/gke-max-shared-clients-per-gpu: "5"  # 2
      volumes:
        - name: stable-diffusion-storage
          persistentVolumeClaim:
            claimName: vol1
      containers:
      - name: stable-diffusion-webui
        image: us-central1-docker.pkg.dev/happyaigc/sd-web-ui-artifacts/sd-webui:inference5
        # image: us-central1-docker.pkg.dev/happyaigc/sd-web-ui-artifacts/sd-webui:train
        resources:
          limits:
            cpu: 1000m    #1800m
            memory: 19Gi  #23Gi
            nvidia.com/gpu: 1
        ports:
          - containerPort: 7860
        # add by yx----启动健康检查
        startupProbe:
          httpGet:
            path: /favicon.ico
            port: 7860
          failureThreshold: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /favicon.ico
            port: 7860
          initialDelaySeconds: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /favicon.ico
            port: 7860
          failureThreshold: 6
          periodSeconds: 10
        # end--by yx
        volumeMounts:
          - mountPath: "/root/stable-diffusion-webui/models/Stable-diffusion"
            name: stable-diffusion-storage
            subPath: sdwebui/models/Stable-diffusion/sd15   # change_other_model
          - mountPath: "/root/stable-diffusion-webui/models/ControlNet"
            name: stable-diffusion-storage
            subPath: sdwebui/models/ControlNet
          - mountPath: "/root/stable-diffusion-webui/models/VAE"
            name: stable-diffusion-storage
            subPath: sdwebui/models/VAE
          - mountPath: "/root/stable-diffusion-webui/models/Lora"
            name: stable-diffusion-storage
            subPath: sdwebui/models/Lora
          - mountPath: "/root/stable-diffusion-webui/models/lora"
            name: stable-diffusion-storage
            subPath: sdwebui/models/trainlora
          - mountPath: "/root/stable-diffusion-webui/embeddings"
            name: stable-diffusion-storage
            subPath: sdwebui/models/embeddings
          - mountPath: "/root/stable-diffusion-webui/hypernetworks"
            name: stable-diffusion-storage
            subPath: sdwebui/models/hypernetworks
          - mountPath: "/root/stable-diffusion-webui/scripts"
            name: stable-diffusion-storage
            subPath: sdwebui/models/scripts
          - mountPath: "/root/stable-diffusion-webui/outputs"
            name: stable-diffusion-storage
            subPath: sdwebui/outputs
          - mountPath: "/root/stable-diffusion-webui/samples"
            name: stable-diffusion-storage
            subPath: sdwebui/samples
          - mountPath: "/root/stable-diffusion-webui/localizations"
            name: stable-diffusion-storage
            subPath: sdwebui/models/localizations
          - mountPath: "/root/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/tags"
            name: stable-diffusion-storage
            subPath: sdwebui/a1111-sd-webui-tagcomplete/tags
          - mountPath: "/root/loopscripts"
            name: stable-diffusion-storage
            subPath: loopscripts

            
