---
apiVersion: v1
data:
  root-password: RGc1bkpyVGVqag==
  root-user: YWRtaW4=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: my-release
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-04-28T04:00:31Z"
  labels:
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: minio
    helm.sh/chart: minio-12.4.1
  name: my-release-minio
  namespace: default
type: Opaque
