apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: stable-diffusion-hpa-sd15
spec:
  minReplicas: 1
  maxReplicas: 30
  metrics:
    - type: External
      external:
        metric:
          name: kubernetes.io|node|accelerator|duty_cycle
          selector:
            matchLabels:
              resource.labels.cluster_name: sd-web-ui-gke2
        target:
          type: AverageValue
          averageValue: 80
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: "stable-diffusion-sd15-deployment"